function feature_table = extract_features( ...
    beats, ...
    rr_intervals, ...
    heart_rate, ...
    r_peaks, ...
    fs, ...
    verbose)

% Default: no console output
if nargin < 6
    verbose = false;
end

%% Number of Beats

num_beats = size(beats,1);

feature_matrix = zeros(num_beats,22);

%% Feature Extraction

for i = 1:num_beats

    beat = beats(i,:);

    %% Statistical Features

    stat = statistical_features(beat);

    %% ECG Features

    if i <= length(rr_intervals)
        rr = rr_intervals(i);
    else
        rr = rr_intervals(end);
    end

    ecg = ecg_features(beat, rr, heart_rate);

    %% FFT Features

    fft_feat = fft_features(beat, fs);

    %% Wavelet Features

    wavelet_feat = wavelet_features(beat);

    %% Combine Features

    feature_matrix(i,:) = ...
        [stat ecg fft_feat wavelet_feat];

end

%% Convert to MATLAB Table

feature_table = array2table(feature_matrix, ...
    'VariableNames', ...
    { ...
    'Mean', ...
    'StdDev', ...
    'Variance', ...
    'RMS', ...
    'Maximum', ...
    'Minimum', ...
    'PeakToPeak', ...
    'RRInterval', ...
    'HeartRate', ...
    'RAmplitude', ...
    'DominantFrequency', ...
    'SpectralEnergy', ...
    'SpectralCentroid', ...
    'SpectralBandwidth', ...
    'BandPowerLow', ...
    'BandPowerMid', ...
    'BandPowerHigh', ...
    'WaveletEnergyA3', ...
    'WaveletEnergyD3', ...
    'WaveletEnergyD2', ...
    'WaveletEnergyD1', ...
    'WaveletEntropy'});

%% Summary (Debug Mode Only)

if verbose

    fprintf("\nFeature Extraction Completed\n");
    fprintf("Number of Beats    : %d\n", num_beats);
    fprintf("Number of Features : %d\n", width(feature_table));

end

end