function stat_features = statistical_features(beat)

stat_features = [ ...
    mean(beat), ...
    std(beat), ...
    var(beat), ...
    rms(beat), ...
    max(beat), ...
    min(beat), ...
    max(beat)-min(beat) ...
    ];

end